function editComboText(cool, muted, mono, warm, light, medium, dark, rarityI, rarityII, rarityIII) {
    
    // retrieve text div IDs
    var coolLightI = document.getElementById("coolLightI");
    var coolLightII = document.getElementById("coolLightII");
    var coolLightIII = document.getElementById("coolLightIII");
    var coolMediumI = document.getElementById("coolMediumI");
    var coolMediumII = document.getElementById("coolMediumII");
    var coolMediumIII = document.getElementById("coolMediumIII");
    var coolDarkI = document.getElementById("coolDarkI");
    var coolDarkII = document.getElementById("coolDarkII");
    var coolDarkIII = document.getElementById("coolDarkIII");
    var warmLightI = document.getElementById("warmLightI");
    var warmLightII = document.getElementById("warmLightII");
    var warmLightIII = document.getElementById("warmLightIII");
    var warmMediumI = document.getElementById("warmMediumI");
    var warmMediumII = document.getElementById("warmMediumII");
    var warmMediumIII = document.getElementById("warmMediumIII");
    var warmDarkI = document.getElementById("warmDarkI");
    var warmDarkII = document.getElementById("warmDarkII");
    var warmDarkIII = document.getElementById("warmDarkIII");
    var monoLightI = document.getElementById("monoLightI");
    var monoLightII = document.getElementById("monoLightII");
    var monoLightIII = document.getElementById("monoLightIII");
    var monoMediumI = document.getElementById("monoMediumI");
    var monoMediumII = document.getElementById("monoMediumII");
    var monoMediumIII = document.getElementById("monoMediumIII");
    var monoDarkI = document.getElementById("monoDarkI");
    var monoDarkII = document.getElementById("monoDarkII");
    var monoDarkIII = document.getElementById("monoDarkIII");
    var mutedLightI = document.getElementById("mutedLightI");
    var mutedLightII = document.getElementById("mutedLightII");
    var mutedLightIII = document.getElementById("mutedLightIII");
    var mutedMediumI = document.getElementById("mutedMediumI");
    var mutedMediumII = document.getElementById("mutedMediumII");
    var mutedMediumIII = document.getElementById("mutedMediumIII");
    var mutedDarkI = document.getElementById("mutedDarkI");
    var mutedDarkII = document.getElementById("mutedDarkII");
    var mutedDarkIII = document.getElementById("mutedDarkIII");
    
    // define the individuals
    var CLI = 0
    var CLII = 0
    var CLIII = 0
    var CMI = 0
    var CMII = 0
    var CMIII = 0
    var CDI = 0
    var CDII = 0
    var CDIII = 0
    var WLI = 0
    var WLII = 0
    var WLIII = 0
    var WMI = 0
    var WMII = 0
    var WMIII = 0
    var WDI = 0
    var WDII = 0
    var WDIII = 0
    var MoLI = 0
    var MoLII = 0
    var MoLIII = 0
    var MoMI = 0
    var MoMII = 0
    var MoMIII = 0
    var MoDI = 0
    var MoDII = 0
    var MoDIII = 0
    var MuLI = 0
    var MuLII = 0
    var MuLIII = 0
    var MuMI = 0
    var MuMII = 0
    var MuMIII = 0
    var MuDI = 0
    var MuDII = 0
    var MuDIII = 0
    
    CLI = cool * light;
    WLI = warm * light;
    MoLI = mono * light;
    MuLI = muted * light;
    MuMI = muted * medium;
    CMI = cool * medium;
    WMI = warm * medium;
    MoMI = mono * medium;
    MoDI = mono * dark;
    MuDI = muted * dark;
    CDI = cool * dark;
    WDI = warm * dark;
    WDII = warm * dark;
    CLII = cool * light;
    WLII = warm * light;
    MoLII = mono * light;
    MuLII = muted * light;
    MuMII = muted * medium;
    CMII = cool * medium;
    WMII = warm * medium;
    MoMII = mono * medium;
    MoDII = mono * dark;
    MuDII = muted * dark;
    CDII = cool * dark;
    CDIII = cool * dark;
    WDIII = warm * dark;
    CLIII = cool * light;
    WLIII = warm * light;
    MoLIII = mono * light;
    MuLIII = muted * light;
    MuMIII = muted * medium;
    CMIII = cool * medium;
    WMIII = warm * medium;
    MoMIII = mono * medium;
    MoDIII = mono * dark;
    MuDIII = muted * dark;
    CLI = CLI * rarityI
    WLI = WLI * rarityI
    MoLI = MoLI * rarityI
    MuLI = MuLI * rarityI
    MuMI = MuMI * rarityI
    CMI = CMI * rarityI
    WMI = WMI * rarityI
    MoMI = MoMI * rarityI
    MoDI = MoDI * rarityI
    MuDI = MuDI * rarityI
    CDI = CDI * rarityI
    WDI = WDI * rarityI
    WDII = WDII * rarityII
    CLII = CLII * rarityII
    WLII = WLII * rarityII
    MoLII = MoLII * rarityII
    MuLII = MuLII * rarityII
    MuMII = MuMII * rarityII
    CMII = CMII * rarityII
    WMII = WMII * rarityII
    MoMII = MoMII * rarityII
    MoDII = MoDII * rarityII
    MuDII = MuDII * rarityII
    CDII = CDII * rarityII
    CDIII = CDIII * rarityIII
    WDIII = WDIII * rarityIII
    CLIII = CLIII * rarityIII
    WLIII = WLIII * rarityIII
    MoLIII = MoLIII * rarityIII
    MuLIII = MuLIII * rarityIII
    MuMIII = MuMIII * rarityIII
    CMIII = CMIII * rarityIII
    WMIII = WMIII * rarityIII
    MoMIII = MoMIII * rarityIII
    MoDIII = MoDIII * rarityIII
    MuDIII = MuDIII * rarityIII
    
    CLI = Math.round((CLI + Number.EPSILON) * 100) / 100
    CLII = Math.round((CLII + Number.EPSILON) * 100) / 100
    CLIII = Math.round((CLIII + Number.EPSILON) * 100) / 100
    CMI = Math.round((CMI + Number.EPSILON) * 100) / 100
    CMII = Math.round((CMII + Number.EPSILON) * 100) / 100
    CMIII = Math.round((CMIII + Number.EPSILON) * 100) / 100
    CDI = Math.round((CDI + Number.EPSILON) * 100) / 100
    CDII = Math.round((CDII + Number.EPSILON) * 100) / 100
    CDIII = Math.round((CDIII + Number.EPSILON) * 100) / 100
    WLI = Math.round((WLI + Number.EPSILON) * 100) / 100
    WLII = Math.round((WLII + Number.EPSILON) * 100) / 100
    WLIII = Math.round((WLIII + Number.EPSILON) * 100) / 100
    WMI = Math.round((WMI + Number.EPSILON) * 100) / 100
    WMII = Math.round((WMII + Number.EPSILON) * 100) / 100
    WMIII = Math.round((WMIII + Number.EPSILON) * 100) / 100
    WDI = Math.round((WDI + Number.EPSILON) * 100) / 100
    WDII = Math.round((WDII + Number.EPSILON) * 100) / 100
    WDIII = Math.round((WDIII + Number.EPSILON) * 100) / 100
    MoLI = Math.round((MoLI + Number.EPSILON) * 100) / 100
    MoLII = Math.round((MoLII + Number.EPSILON) * 100) / 100
    MoLIII = Math.round((MoLIII + Number.EPSILON) * 100) / 100
    MoMI = Math.round((MoMI + Number.EPSILON) * 100) / 100
    MoMII = Math.round((MoMII + Number.EPSILON) * 100) / 100
    MoMIII = Math.round((MoMIII + Number.EPSILON) * 100) / 100
    MoDI = Math.round((MoDI + Number.EPSILON) * 100) / 100
    MoDII = Math.round((MoDII + Number.EPSILON) * 100) / 100
    MoDIII = Math.round((MoDIII + Number.EPSILON) * 100) / 100
    MuLI = Math.round((MuLI + Number.EPSILON) * 100) / 100
    MuLII = Math.round((MuLII + Number.EPSILON) * 100) / 100
    MuLIII = Math.round((MuLIII + Number.EPSILON) * 100) / 100
    MuMI = Math.round((MuMI + Number.EPSILON) * 100) / 100
    MuMII = Math.round((MuMII + Number.EPSILON) * 100) / 100
    MuMIII = Math.round((MuMIII + Number.EPSILON) * 100) / 100
    MuDI = Math.round((MuDI + Number.EPSILON) * 100) / 100
    MuDII = Math.round((MuDII + Number.EPSILON) * 100) / 100
    MuDIII = Math.round((MuDIII + Number.EPSILON) * 100) / 100
    
    coolLightI.textContent = CLI + "%";
    coolLightII.textContent = CLII + "%";
    coolLightIII.textContent = CLIII + "%";
    coolMediumI.textContent = CMI + "%";
    coolMediumII.textContent = CMII + "%";
    coolMediumIII.textContent = CMIII + "%";
    coolDarkI.textContent = CDI + "%";
    coolDarkII.textContent = CDII + "%";
    coolDarkIII.textContent = CDIII + "%";
    
    warmLightI.textContent = WLI + "%";
    warmLightII.textContent = WLII + "%";
    warmLightIII.textContent = WLIII + "%";
    warmMediumI.textContent = WMI + "%";
    warmMediumII.textContent = WMII + "%";
    warmMediumIII.textContent = WMIII + "%";
    warmDarkI.textContent = WDI + "%";
    warmDarkII.textContent = WDII + "%";
    warmDarkIII.textContent = WDIII + "%";
    
    monoLightI.textContent = MoLI + "%";
    monoLightII.textContent = MoLII + "%";
    monoLightIII.textContent = MoLIII + "%";
    monoMediumI.textContent = MoMI + "%";
    monoMediumII.textContent = MoMII + "%";
    monoMediumIII.textContent = MoMIII + "%";
    monoDarkI.textContent = MoDI + "%";
    monoDarkII.textContent = MoDII + "%";
    monoDarkIII.textContent = MoDIII + "%";
    
    mutedLightI.textContent = MuLI + "%";
    mutedLightII.textContent = MuLII + "%";
    mutedLightIII.textContent = MuLIII + "%";
    mutedMediumI.textContent = MuMI + "%";
    mutedMediumII.textContent = MuMII + "%";
    mutedMediumIII.textContent = MuMIII + "%";
    mutedDarkI.textContent = MuDI + "%";
    mutedDarkII.textContent = MuDII + "%";
    mutedDarkIII.textContent = MuDIII + "%";
    
}