function editBaseText(cool, muted, mono, warm, light, medium, dark, rarityI, rarityII, rarityIII) {
    
    // retrieve text div IDs
    var Acanthite = document.getElementById("Acanthite");
    var Almond = document.getElementById("Almond");
    var Amber = document.getElementById("Amber");
    var Antler = document.getElementById("Antler");
    var Apricot = document.getElementById("Apricot");
    var Argent = document.getElementById("Argent");
    var Arkose = document.getElementById("Arkose");
    var Ashen = document.getElementById("Ashen");
    var Auburn = document.getElementById("Auburn");
    var Beige = document.getElementById("Beige");
    var Biotite = document.getElementById("Biotite");
    var Birch = document.getElementById("Birch");
    var Black = document.getElementById("Black");
    var Blonde = document.getElementById("Blonde");
    var Blue = document.getElementById("Blue");
    var Brass = document.getElementById("Brass");
    var Bronze = document.getElementById("Bronze");
    var Brown = document.getElementById("Brown");
    var Buff = document.getElementById("Buff");
    var Calcite = document.getElementById("Calcite");
    var Caramel = document.getElementById("Caramel");
    var Chert = document.getElementById("Chert");
    var Chestnut = document.getElementById("Chestnut");
    var Chocolate = document.getElementById("Chocolate");
    var Chromium = document.getElementById("Chromium");
    var Cocoa = document.getElementById("Cocoa");
    var Cream = document.getElementById("Cream");
    var CreamDarker = document.getElementById("CreamDarker");
    var CreamLighter = document.getElementById("CreamLighter");
    var DarkBrown = document.getElementById("DarkBrown");
    var Denim = document.getElementById("Denim");
    var Dinar = document.getElementById("Dinar");
    var Diorite = document.getElementById("Diorite");
    var Doubloon = document.getElementById("Doubloon");
    var Dravit = document.getElementById("Dravit");
    var Ducat = document.getElementById("Ducat");
    var Dust = document.getElementById("Dust");
    var Ebony = document.getElementById("Ebony");
    var Feldspar = document.getElementById("Feldspar");
    var Flint = document.getElementById("Flint");
    var Fox = document.getElementById("Fox");
    var Galena = document.getElementById("Galena");
    var Glaucous = document.getElementById("Glaucous");
    var Gold = document.getElementById("Gold");
    var GoldDarker = document.getElementById("GoldDarker");
    var GoldLighter = document.getElementById("GoldLighter");
    var Goldenrod = document.getElementById("Goldenrod");
    var Gray = document.getElementById("Gray");
    var GrayDarker = document.getElementById("GrayDarker");
    var GrayLighter = document.getElementById("GrayLighter");
    var Grulla = document.getElementById("Grulla");
    var Henna = document.getElementById("Henna");
    var Honey = document.getElementById("Honey");
    var Honeydew = document.getElementById("Honeydew");
    var Howlite = document.getElementById("Howlite");
    var Iridium = document.getElementById("Iridium");
    var Isabel = document.getElementById("Isabel");
    var Jacinthe = document.getElementById("Jacinthe");
    var Jet = document.getElementById("Jet");
    var Khaki = document.getElementById("Khaki");
    var Lavender = document.getElementById("Lavender");
    var Lilac = document.getElementById("Lilac");
    var Lily = document.getElementById("Lily");
    var Liver = document.getElementById("Liver");
    var Magnolia = document.getElementById("Magnolia");
    var Maltese = document.getElementById("Maltese");
    var Marengo = document.getElementById("Marengo");
    var Melchior = document.getElementById("Melchior");
    var Mojave = document.getElementById("Mojave");
    var Nepheline = document.getElementById("Nepheline");
    var Nocturne = document.getElementById("Nocturne");
    var Obsidian = document.getElementById("Obsidian");
    var Onyx = document.getElementById("Onyx");
    var Opal = document.getElementById("Opal");
    var Oroide = document.getElementById("Oroide");
    var Pale = document.getElementById("Pale");
    var Peach = document.getElementById("Peach");
    var Pearl = document.getElementById("Pearl");
    var Pecan = document.getElementById("Pecan");
    var Pewter = document.getElementById("Pewter");
    var Piasa = document.getElementById("Piasa");
    var Pyrope = document.getElementById("Pyrope");
    var Quartz = document.getElementById("Quartz");
    var Realgar = document.getElementById("Realgar");
    var Red = document.getElementById("Red");
    var Rime = document.getElementById("Rime");
    var Russet = document.getElementById("Russet");
    var Rust = document.getElementById("Rust");
    var Saffron = document.getElementById("Saffron");
    var Sandy = document.getElementById("Sandy");
    var Sarder = document.getElementById("Sarder");
    var Seal = document.getElementById("Seal");
    var Sepia = document.getElementById("Sepia");
    var Serpentine = document.getElementById("Serpentine");
    var Shell = document.getElementById("Shell");
    var Silver = document.getElementById("Silver");
    var Siqoq = document.getElementById("Siqoq");
    var Skarn = document.getElementById("Skarn");
    var Sky = document.getElementById("Sky");
    var Slate = document.getElementById("Slate");
    var Snow = document.getElementById("Snow");
    var Sphalerite = document.getElementById("Sphalerite");
    var Steele = document.getElementById("Steele");
    var Sterling = document.getElementById("Sterling");
    var StripedFlint = document.getElementById("StripedFlint");
    var Sulphur = document.getElementById("Sulphur");
    var Tawny = document.getElementById("Tawny");
    var Teardrop = document.getElementById("Teardrop");
    var Titanium = document.getElementById("Titanium");
    var Tombac = document.getElementById("Tombac");
    var Tuff = document.getElementById("Tuff");
    var Tumbleweed = document.getElementById("Tumbleweed");
    var Vanilla = document.getElementById("Vanilla");
    var White = document.getElementById("White");
    var Willow = document.getElementById("Willow");
    var Wulfenite = document.getElementById("Wulfenite");
    var Yellow = document.getElementById("Yellow");
    var Zircon = document.getElementById("Zircon");
    
    // define the individuals
    var CLI = 0
    var CLII = 0
    var CLIII = 0
    var CMI = 0
    var CMII = 0
    var CMIII = 0
    var CDI = 0
    var CDII = 0
    var CDIII = 0
    var WLI = 0
    var WLII = 0
    var WLIII = 0
    var WMI = 0
    var WMII = 0
    var WMIII = 0
    var WDI = 0
    var WDII = 0
    var WDIII = 0
    var MoLI = 0
    var MoLII = 0
    var MoLIII = 0
    var MoMI = 0
    var MoMII = 0
    var MoMIII = 0
    var MoDI = 0
    var MoDII = 0
    var MoDIII = 0
    var MuLI = 0
    var MuLII = 0
    var MuLIII = 0
    var MuMI = 0
    var MuMII = 0
    var MuMIII = 0
    var MuDI = 0
    var MuDII = 0
    var MuDIII = 0
    
    CLI = cool * light;
    WLI = warm * light;
    MoLI = mono * light;
    MuLI = muted * light;
    MuMI = muted * medium;
    CMI = cool * medium;
    WMI = warm * medium;
    MoMI = mono * medium;
    MoDI = mono * dark;
    MuDI = muted * dark;
    CDI = cool * dark;
    WDI = warm * dark;
    WDII = warm * dark;
    CLII = cool * light;
    WLII = warm * light;
    MoLII = mono * light;
    MuLII = muted * light;
    MuMII = muted * medium;
    CMII = cool * medium;
    WMII = warm * medium;
    MoMII = mono * medium;
    MoDII = mono * dark;
    MuDII = muted * dark;
    CDII = cool * dark;
    CDIII = cool * dark;
    WDIII = warm * dark;
    CLIII = cool * light;
    WLIII = warm * light;
    MoLIII = mono * light;
    MuLIII = muted * light;
    MuMIII = muted * medium;
    CMIII = cool * medium;
    WMIII = warm * medium;
    MoMIII = mono * medium;
    MoDIII = mono * dark;
    MuDIII = muted * dark;
    
    CLI = CLI * rarityI
    WLI = WLI * rarityI
    MoLI = MoLI * rarityI
    MuLI = MuLI * rarityI
    MuMI = MuMI * rarityI
    CMI = CMI * rarityI
    WMI = WMI * rarityI
    MoMI = MoMI * rarityI
    MoDI = MoDI * rarityI
    MuDI = MuDI * rarityI
    CDI = CDI * rarityI
    WDI = WDI * rarityI
    WDII = WDII * rarityII
    CLII = CLII * rarityII
    WLII = WLII * rarityII
    MoLII = MoLII * rarityII
    MuLII = MuLII * rarityII
    MuMII = MuMII * rarityII
    CMII = CMII * rarityII
    WMII = WMII * rarityII
    MoMII = MoMII * rarityII
    MoDII = MoDII * rarityII
    MuDII = MuDII * rarityII
    CDII = CDII * rarityII
    CDIII = CDIII * rarityIII
    WDIII = WDIII * rarityIII
    CLIII = CLIII * rarityIII
    WLIII = WLIII * rarityIII
    MoLIII = MoLIII * rarityIII
    MuLIII = MuLIII * rarityIII
    MuMIII = MuMIII * rarityIII
    CMIII = CMIII * rarityIII
    WMIII = WMIII * rarityIII
    MoMIII = MoMIII * rarityIII
    MoDIII = MoDIII * rarityIII
    MuDIII = MuDIII * rarityIII
    
    CLI = CLI * 0.5
    WLI = WLI * 0.25
    MoLI = MoLI * 0.25
    MuLI = MuLI * 0.25
    MuMI = MuMI * 0.25
    CMI = CMI * 0.5
    WMI = WMI * 0.25
    MoMI = MoMI * 0.25
    MoDI = MoDI * 0.25
    MuDI = MuDI * 0.25
    CDI = CDI * 0.5
    WDI = WDI * 0.25
    WDII = WDII * 0.2
    CLII = CLII * 0.33
    WLII = WLII * 0.2
    MoLII = MoLII * 0.2
    MuLII = MuLII * 0.2
    MuMII = MuMII * 0.2
    CMII = CMII * 0.33
    WMII = WMII * 0.2
    MoMII = MoMII * 0.2
    MoDII = MoDII * 0.2
    MuDII = MuDII * 0.2
    CDII = CDII * 0.33
    CDIII = CDIII * 1
    WDIII = WDIII * 0.5
    CLIII = CLIII * 1
    WLIII = WLIII * 0.5
    MoLIII = MoLIII * 0.5
    MuLIII = MuLIII * 0.5
    MuMIII = MuMIII * 0.5
    CMIII = CMIII * 1
    WMIII = WMIII * 0.33
    MoMIII = MoMIII * 0.5
    MoDIII = MoDIII * 0.5
    MuDIII = MuDIII * 0.5
    
    CLI = Math.round((CLI + Number.EPSILON) * 100) / 100
    CLII = Math.round((CLII + Number.EPSILON) * 100) / 100
    CLIII = Math.round((CLIII + Number.EPSILON) * 100) / 100
    CMI = Math.round((CMI + Number.EPSILON) * 100) / 100
    CMII = Math.round((CMII + Number.EPSILON) * 100) / 100
    CMIII = Math.round((CMIII + Number.EPSILON) * 100) / 100
    CDI = Math.round((CDI + Number.EPSILON) * 100) / 100
    CDII = Math.round((CDII + Number.EPSILON) * 100) / 100
    CDIII = Math.round((CDIII + Number.EPSILON) * 100) / 100
    WLI = Math.round((WLI + Number.EPSILON) * 100) / 100
    WLII = Math.round((WLII + Number.EPSILON) * 100) / 100
    WLIII = Math.round((WLIII + Number.EPSILON) * 100) / 100
    WMI = Math.round((WMI + Number.EPSILON) * 100) / 100
    WMII = Math.round((WMII + Number.EPSILON) * 100) / 100
    WMIII = Math.round((WMIII + Number.EPSILON) * 100) / 100
    WDI = Math.round((WDI + Number.EPSILON) * 100) / 100
    WDII = Math.round((WDII + Number.EPSILON) * 100) / 100
    WDIII = Math.round((WDIII + Number.EPSILON) * 100) / 100
    MoLI = Math.round((MoLI + Number.EPSILON) * 100) / 100
    MoLII = Math.round((MoLII + Number.EPSILON) * 100) / 100
    MoLIII = Math.round((MoLIII + Number.EPSILON) * 100) / 100
    MoMI = Math.round((MoMI + Number.EPSILON) * 100) / 100
    MoMII = Math.round((MoMII + Number.EPSILON) * 100) / 100
    MoMIII = Math.round((MoMIII + Number.EPSILON) * 100) / 100
    MoDI = Math.round((MoDI + Number.EPSILON) * 100) / 100
    MoDII = Math.round((MoDII + Number.EPSILON) * 100) / 100
    MoDIII = Math.round((MoDIII + Number.EPSILON) * 100) / 100
    MuLI = Math.round((MuLI + Number.EPSILON) * 100) / 100
    MuLII = Math.round((MuLII + Number.EPSILON) * 100) / 100
    MuLIII = Math.round((MuLIII + Number.EPSILON) * 100) / 100
    MuMI = Math.round((MuMI + Number.EPSILON) * 100) / 100
    MuMII = Math.round((MuMII + Number.EPSILON) * 100) / 100
    MuMIII = Math.round((MuMIII + Number.EPSILON) * 100) / 100
    MuDI = Math.round((MuDI + Number.EPSILON) * 100) / 100
    MuDII = Math.round((MuDII + Number.EPSILON) * 100) / 100
    MuDIII = Math.round((MuDIII + Number.EPSILON) * 100) / 100
    
    Acanthite.textContent = "Acanthite: " + MoMII + "%";
    Almond.textContent = "Almond: " + MuLII + "%";
    Amber.textContent = "Amber: " + WDI + "%";
    Antler.textContent = "Antler: " + MuMII + "%";
    Apricot.textContent = "Apricot: " + MuLI + "%";
    Argent.textContent = "Argent: " + MoLIII + "%";
    Arkose.textContent = "Arkose: " + WLII + "%";
    Ashen.textContent = "Ashen: " + MoMI + "%";
    Auburn.textContent = "Auburn: " + WDII + "%";
    Beige.textContent = "Beige: " + MuLI + "%";
    Biotite.textContent = "Biotite: " + MoDII + "%";
    Birch.textContent = "Birch: " + MoMI + "%";
    Black.textContent = "Black: " + MoDI + "%";
    Blonde.textContent = "Blonde: " + MuMII + "%";
    Blue.textContent = "Blue: " + CMI + "%";
    Brass.textContent = "Brass: " + WMI + "%";
    Bronze.textContent = "Bronze: " + MuDIII + "%";
    Brown.textContent = "Brown: " + WDI + "%";
    Buff.textContent = "Buff: " + MuLII + "%";
    Calcite.textContent = "Calcite: " + WLII + "%";
    Caramel.textContent = "Caramel: " + MuDI + "%";
    Chert.textContent = "Chert: " + MoMII + "%";
    Chestnut.textContent = "Chestnut: " + MuDI + "%";
    Chocolate.textContent = "Chocolate: " + MuDI + "%";
    Chromium.textContent = "Chromium: " + MoLIII + "%";
    Cocoa.textContent = "Cocoa: " + MuDII + "%";
    Cream.textContent = "Cream: " + MuMI + "%";
    CreamDarker.textContent = "Cream Darker: " + MuMI + "%";
    CreamLighter.textContent = "Cream Lighter: " + MuLI + "%";
    DarkBrown.textContent = "Dark Brown: " + MuDI + "%";
    Denim.textContent = "Denim: " + CDII + "%";
    Dinar.textContent = "Dinar: " + WDII + "%";
    Diorite.textContent = "Diorite: " + CMII + "%";
    Doubloon.textContent = "Doubloon: " + WMII + "%";
    Dravit.textContent = "Dravit: " + WDII + "%";
    Ducat.textContent = "Ducat: " + WLII + "%";
    Dust.textContent = "Dust: " + MoLI + "%";
    Ebony.textContent = "Ebony: " + MuDII + "%";
    Feldspar.textContent = "Feldspar: " + MuLII + "%";
    Flint.textContent = "Flint: " + MoMIII + "%";
    Fox.textContent = "Fox: " + WMIII + "%";
    Galena.textContent = "Galena: " + CMII + "%";
    Glaucous.textContent = "Glaucous: " + CLI + "%";
    Gold.textContent = "Gold: " + WMI + "%";
    GoldDarker.textContent = "Gold Darker: " + WMI + "%";
    GoldLighter.textContent = "Gold Lighter: " + WLI + "%";
    Goldenrod.textContent = "Goldenrod: " + WLI + "%";
    Gray.textContent = "Gray: " + MoDI + "%";
    GrayDarker.textContent = "Gray Darker: " + MoDI + "%";
    GrayLighter.textContent = "Gray Lighter: " + MoMI + "%";
    Grulla.textContent = "Grulla: " + CMIII + "%";
    Henna.textContent = "Henna: " + WDI + "%";
    Honey.textContent = "Honey: " + MuMI + "%";
    Honeydew.textContent = "Honeydew: " + CLI + "%";
    Howlite.textContent = "Howlite: " + MoMI + "%";
    Iridium.textContent = "Iridium: " + MoDIII + "%";
    Isabel.textContent = "Isabel: " + MuLII + "%";
    Jacinthe.textContent = "Jacinthe: " + WLII + "%";
    Jet.textContent = "Jet: " + MoDI + "%";
    Khaki.textContent = "Khaki: " + CMI + "%";
    Lavender.textContent = "Lavender: " + CLII + "%";
    Lilac.textContent = "Lilac: " + CDII + "%";
    Lily.textContent = "Lily: " + MuMIII + "%";
    Liver.textContent = "Liver: " + WDI + "%";
    Magnolia.textContent = "Magnolia: " + WLI + "%";
    Maltese.textContent = "Maltese: " + CMII + "%";
    Marengo.textContent = "Marengo: " + CDI + "%";
    Melchior.textContent = "Melchior: " + MoLII + "%";
    Mojave.textContent = "Mojave: " + WMIII + "%";
    Nepheline.textContent = "Nepheline: " + MoLII + "%";
    Nocturne.textContent = "Nocturne: " + CDII + "%";
    Obsidian.textContent = "Obsidian: " + MoDII + "%";
    Onyx.textContent = "Onyx: " + MoDII + "%";
    Opal.textContent = "Opal: " + CLIII + "%";
    Oroide.textContent = "Oroide: " + MuDII + "%";
    Pale.textContent = "Pale: " + CLII + "%";
    Peach.textContent = "Peach: " + MuLII + "%";
    Pearl.textContent = "Pearl: " + MuMIII + "%";
    Pecan.textContent = "Pecan: " + MuDII + "%";
    Pewter.textContent = "Pewter: " + MoDII + "%";
    Piasa.textContent = "Piasa: " + WLIII + "%";
    Pyrope.textContent = "Pyrope: " + WDIII + "%";
    Quartz.textContent = "Quartz: " + MoLI + "%";
    Realgar.textContent = "Realgar: " + WDIII + "%";
    Red.textContent = "Red: " + WMI + "%";
    Rime.textContent = "Rime: " + MoLII + "%";
    Russet.textContent = "Russet: " + WDII + "%";
    Rust.textContent = "Rust: " + WMII + "%";
    Saffron.textContent = "Saffron: " + WMII + "%";
    Sandy.textContent = "Sandy: " + MuMII + "%";
    Sarder.textContent = "Sarder: " + WDII + "%";
    Seal.textContent = "Seal: " + MuDIII + "%";
    Sepia.textContent = "Sepia: " + MuDII + "%";
    Serpentine.textContent = "Serpentine: " + CDIII + "%";
    Shell.textContent = "Shell: " + MuLI + "%";
    Silver.textContent = "Silver: " + MoMII + "%";
    Siqoq.textContent = "Siqoq: " + MoLII + "%";
    Skarn.textContent = "Skarn: " + CDI + "%";
    Sky.textContent = "Sky: " + CLII + "%";
    Slate.textContent = "Slate: " + MoDIII + "%";
    Snow.textContent = "Snow: " + MoLI + "%";
    Sphalerite.textContent = "Sphalerite: " + MoDII + "%";
    Steele.textContent = "Steele: " + MoMII + "%";
    Sterling.textContent = "Sterling: " + MoMII + "%";
    StripedFlint.textContent = "Striped Flint: " + MoMIII + "%";
    Sulphur.textContent = "Sulphur: " + WMII + "%";
    Tawny.textContent = "Tawny: " + WMII + "%";
    Teardrop.textContent = "Teardrop: " + MuLIII + "%";
    Titanium.textContent = "Titanium: " + MoLII + "%";
    Tombac.textContent = "Tombac: " + WLIII + "%";
    Tuff.textContent = "Tuff: " + MuMII + "%";
    Tumbleweed.textContent = "Tumbleweed: " + WLI + "%";
    Vanilla.textContent = "Vanilla: " + MuMII + "%";
    White.textContent = "White: " + MoLI + "%";
    Willow.textContent = "Willow: " + MuMI + "%";
    Wulfenite.textContent = "Wulfenite: " + WMIII + "%";
    Yellow.textContent = "Yellow: " + WLII + "%";
    Zircon.textContent = "Zircon: " + MuLIII + "%";
    
}